"""empty message

Revision ID: 550fee61384e
Revises: None
Create Date: 2015-12-04 09:46:22.701656

"""

# revision identifiers, used by Alembic.
revision = '550fee61384e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('construction_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('descr', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('constructor', sa.Text(), nullable=True),
    sa.Column('execution', sa.Text(), nullable=True),
    sa.Column('location_descr', sa.Text(), nullable=True),
    sa.Column('restriction', sa.Text(), nullable=True),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('begin', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('licence_name', sa.Text(), nullable=True),
    sa.Column('licence_url', sa.Text(), nullable=True),
    sa.Column('licence_owner', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('construction_site')
    ### end Alembic commands ###
